"""
Comprehensive biblical character data for La Sacra Bibbia Knowledge Graph.
Includes all named characters with narrative significance from both
Old and New Testaments, plus deuterocanonical books.
"""

# Groups: patriarch, matriarch, king, queen, prophet, judge, apostle,
#         evangelist, leader, priest, angel, demon, warrior, other
# Testament: OT, NT

CHARACTERS = {
    # ═══════════════════════════════════════════════════════════════
    #  GENESIS — Primeval history
    # ═══════════════════════════════════════════════════════════════
    "Adam":          {"group": "patriarch", "testament": "OT", "desc": "First man, created by God"},
    "Eve":           {"group": "matriarch", "testament": "OT", "desc": "First woman, wife of Adam"},
    "Cain":          {"group": "other",     "testament": "OT", "desc": "First son of Adam, murdered Abel"},
    "Abel":          {"group": "other",     "testament": "OT", "desc": "Second son of Adam, killed by Cain"},
    "Seth":          {"group": "patriarch", "testament": "OT", "desc": "Third son of Adam and Eve"},
    "Enosh":         {"group": "patriarch", "testament": "OT", "desc": "Son of Seth, grandson of Adam"},
    "Kenan":         {"group": "patriarch", "testament": "OT", "desc": "Son of Enosh, antediluvian patriarch (Cainan in NT)"},
    "Mahalalel":     {"group": "patriarch", "testament": "OT", "desc": "Son of Kenan, antediluvian patriarch"},
    "Jared":         {"group": "patriarch", "testament": "OT", "desc": "Son of Mahalalel, father of Enoch"},
    "Enoch":         {"group": "patriarch", "testament": "OT", "desc": "Walked with God, taken to heaven"},
    "Methuselah":    {"group": "patriarch", "testament": "OT", "desc": "Longest-lived man (969 years)"},
    "Lamech":        {"group": "patriarch", "testament": "OT", "desc": "Father of Noah"},
    "Noah":          {"group": "patriarch", "testament": "OT", "desc": "Builder of the Ark, survived the Flood"},
    "Shem":          {"group": "patriarch", "testament": "OT", "desc": "Son of Noah, ancestor of Semitic peoples"},
    "Ham":           {"group": "patriarch", "testament": "OT", "desc": "Son of Noah, father of Canaan"},
    "Japheth":       {"group": "patriarch", "testament": "OT", "desc": "Son of Noah"},
    # Sons of Japheth (Gen 10)
    "Gomer":         {"group": "patriarch", "testament": "OT", "desc": "Son of Japheth, ancestor of Cimmerians"},
    "Magog":         {"group": "patriarch", "testament": "OT", "desc": "Son of Japheth, eponym of northern peoples"},
    "Madai":         {"group": "patriarch", "testament": "OT", "desc": "Son of Japheth, ancestor of Medes"},
    "Javan":         {"group": "patriarch", "testament": "OT", "desc": "Son of Japheth, ancestor of Ionians/Greeks"},
    "Tubal":         {"group": "patriarch", "testament": "OT", "desc": "Son of Japheth"},
    "Meshech":       {"group": "patriarch", "testament": "OT", "desc": "Son of Japheth"},
    "Tiras":         {"group": "patriarch", "testament": "OT", "desc": "Son of Japheth"},
    # Sons of Ham (Gen 10)
    "Cush":          {"group": "patriarch", "testament": "OT", "desc": "Son of Ham, father of Nimrod, eponym of Cushites"},
    "Mizraim":       {"group": "patriarch", "testament": "OT", "desc": "Son of Ham, eponym of Egypt"},
    "Put":           {"group": "patriarch", "testament": "OT", "desc": "Son of Ham, eponym of Libyans"},
    "Canaan":        {"group": "patriarch", "testament": "OT", "desc": "Son of Ham, cursed by Noah, ancestor of Canaanites"},
    "Nimrod":        {"group": "king",      "testament": "OT", "desc": "Mighty hunter, king of Babel; son of Cush"},
    # Sons of Shem (Gen 10)
    "Elam":          {"group": "patriarch", "testament": "OT", "desc": "Son of Shem, eponym of Elamites"},
    "Asshur":        {"group": "patriarch", "testament": "OT", "desc": "Son of Shem, eponym of Assyrians"},
    "Arphaxad":      {"group": "patriarch", "testament": "OT", "desc": "Son of Shem, ancestor of Abraham"},
    "Lud":           {"group": "patriarch", "testament": "OT", "desc": "Son of Shem, eponym of Lydians"},
    "Aram":          {"group": "patriarch", "testament": "OT", "desc": "Son of Shem, eponym of Arameans"},
    # Shem → Terah bridge (Gen 11)
    "Shelah":        {"group": "patriarch", "testament": "OT", "desc": "Son of Arphaxad, in line from Shem to Abraham"},
    "Eber":          {"group": "patriarch", "testament": "OT", "desc": "Son of Shelah, eponym of Hebrews"},
    "Peleg":         {"group": "patriarch", "testament": "OT", "desc": "Son of Eber; in his days the earth was divided"},
    "Reu":           {"group": "patriarch", "testament": "OT", "desc": "Son of Peleg, in line from Shem to Abraham"},
    "Serug":         {"group": "patriarch", "testament": "OT", "desc": "Son of Reu, great-grandfather of Abraham"},
    "Nahor son of Serug": {"group": "patriarch", "testament": "OT", "desc": "Son of Serug, grandfather of Abraham"},
    # ═══════════════════════════════════════════════════════════════
    #  GENESIS — Patriarchs & Matriarchs
    # ═══════════════════════════════════════════════════════════════
    "Terah":         {"group": "patriarch", "testament": "OT", "desc": "Father of Abraham"},
    "Abraham":       {"group": "patriarch", "testament": "OT", "desc": "Father of nations, friend of God"},
    "Sarah":         {"group": "matriarch", "testament": "OT", "desc": "Wife of Abraham, mother of Isaac"},
    "Hagar":         {"group": "matriarch", "testament": "OT", "desc": "Handmaid of Sarah, mother of Ishmael"},
    "Lot":           {"group": "other",     "testament": "OT", "desc": "Nephew of Abraham, escaped Sodom"},
    "Melchizedek":   {"group": "priest",    "testament": "OT", "desc": "King of Salem, priest of God Most High"},
    "Ishmael":       {"group": "patriarch", "testament": "OT", "desc": "Son of Abraham and Hagar"},
    "Isaac":         {"group": "patriarch", "testament": "OT", "desc": "Son of Abraham and Sarah"},
    "Rebekah":       {"group": "matriarch", "testament": "OT", "desc": "Wife of Isaac, mother of Jacob and Esau"},
    "Laban":         {"group": "other",     "testament": "OT", "desc": "Brother of Rebekah, father of Leah and Rachel"},
    "Jacob":         {"group": "patriarch", "testament": "OT", "desc": "Son of Isaac, father of 12 tribes of Israel"},
    "Esau":          {"group": "other",     "testament": "OT", "desc": "Twin brother of Jacob, father of Edomites"},
    "Leah":          {"group": "matriarch", "testament": "OT", "desc": "First wife of Jacob"},
    "Rachel":        {"group": "matriarch", "testament": "OT", "desc": "Beloved wife of Jacob, mother of Joseph"},
    # 12 sons of Jacob (tribes)
    "Reuben":        {"group": "patriarch", "testament": "OT", "desc": "Firstborn of Jacob and Leah"},
    "Simeon":        {"group": "patriarch", "testament": "OT", "desc": "Second son of Jacob and Leah"},
    "Levi":          {"group": "patriarch", "testament": "OT", "desc": "Third son of Jacob, ancestor of priests"},
    "Judah":         {"group": "patriarch", "testament": "OT", "desc": "Fourth son of Jacob, ancestor of David"},
    "Dan":           {"group": "patriarch", "testament": "OT", "desc": "Son of Jacob and Bilhah"},
    "Naphtali":      {"group": "patriarch", "testament": "OT", "desc": "Son of Jacob and Bilhah"},
    "Gad":           {"group": "patriarch", "testament": "OT", "desc": "Son of Jacob and Zilpah"},
    "Asher":         {"group": "patriarch", "testament": "OT", "desc": "Son of Jacob and Zilpah"},
    "Issachar":      {"group": "patriarch", "testament": "OT", "desc": "Son of Jacob and Leah"},
    "Zebulun":       {"group": "patriarch", "testament": "OT", "desc": "Son of Jacob and Leah"},
    "Joseph":        {"group": "patriarch", "testament": "OT", "desc": "Son of Jacob and Rachel, ruler in Egypt"},
    "Benjamin":      {"group": "patriarch", "testament": "OT", "desc": "Youngest son of Jacob and Rachel"},
    "Dinah":         {"group": "other",     "testament": "OT", "desc": "Daughter of Jacob and Leah"},
    "Tamar":         {"group": "matriarch", "testament": "OT", "desc": "Daughter-in-law of Judah, in lineage of David"},
    "Potiphar":      {"group": "other",     "testament": "OT", "desc": "Egyptian officer, master of Joseph"},
    "Asenath":       {"group": "matriarch", "testament": "OT", "desc": "Egyptian wife of Joseph"},
    "Ephraim":       {"group": "patriarch", "testament": "OT", "desc": "Son of Joseph, major tribe"},
    "Manasseh":      {"group": "patriarch", "testament": "OT", "desc": "Son of Joseph, major tribe"},
    # ═══════════════════════════════════════════════════════════════
    #  EXODUS — DEUTERONOMY
    # ═══════════════════════════════════════════════════════════════
    "Moses":         {"group": "leader",    "testament": "OT", "desc": "Deliverer of Israel, received the Law"},
    "Aaron":         {"group": "priest",    "testament": "OT", "desc": "First High Priest, brother of Moses"},
    "Miriam":        {"group": "prophet",   "testament": "OT", "desc": "Prophetess, sister of Moses and Aaron"},
    "Pharaoh":       {"group": "king",      "testament": "OT", "desc": "King of Egypt during the Exodus"},
    "Zipporah":      {"group": "matriarch", "testament": "OT", "desc": "Wife of Moses"},
    "Jethro":        {"group": "priest",    "testament": "OT", "desc": "Father-in-law of Moses, priest of Midian"},
    "Joshua":        {"group": "leader",    "testament": "OT", "desc": "Successor of Moses, conquered Canaan"},
    "Caleb":         {"group": "leader",    "testament": "OT", "desc": "Faithful spy, entered the Promised Land"},
    "Korah":         {"group": "other",     "testament": "OT", "desc": "Led rebellion against Moses"},
    "Balaam":        {"group": "prophet",   "testament": "OT", "desc": "Pagan prophet hired to curse Israel"},
    "Balak":         {"group": "king",      "testament": "OT", "desc": "King of Moab who hired Balaam"},
    "Phinehas":      {"group": "priest",    "testament": "OT", "desc": "Zealous grandson of Aaron"},
    "Bezalel":       {"group": "other",     "testament": "OT", "desc": "Craftsman who built the Tabernacle"},
    "Nadab":         {"group": "priest",    "testament": "OT", "desc": "Son of Aaron, died offering strange fire"},
    "Abihu":         {"group": "priest",    "testament": "OT", "desc": "Son of Aaron, died offering strange fire"},
    "Eleazar":       {"group": "priest",    "testament": "OT", "desc": "Son of Aaron, succeeded as High Priest"},
    # ═══════════════════════════════════════════════════════════════
    #  JOSHUA — JUDGES — RUTH
    # ═══════════════════════════════════════════════════════════════
    "Rahab":         {"group": "other",     "testament": "OT", "desc": "Prostitute of Jericho who hid the spies"},
    "Achan":         {"group": "other",     "testament": "OT", "desc": "Stole from Jericho, punished by God"},
    "Othniel":       {"group": "judge",     "testament": "OT", "desc": "First judge of Israel"},
    "Ehud":          {"group": "judge",     "testament": "OT", "desc": "Left-handed judge who killed Eglon"},
    "Shamgar":       {"group": "judge",     "testament": "OT", "desc": "Judge who killed 600 Philistines"},
    "Deborah":       {"group": "judge",     "testament": "OT", "desc": "Judge and prophetess of Israel"},
    "Barak":         {"group": "warrior",   "testament": "OT", "desc": "Military commander under Deborah"},
    "Jael":          {"group": "other",     "testament": "OT", "desc": "Killed Sisera with a tent peg"},
    "Sisera":        {"group": "warrior",   "testament": "OT", "desc": "Canaanite commander defeated by Deborah"},
    "Gideon":        {"group": "judge",     "testament": "OT", "desc": "Judge who defeated Midianites with 300 men"},
    "Abimelech":     {"group": "king",      "testament": "OT", "desc": "Son of Gideon, self-proclaimed king"},
    "Jephthah":      {"group": "judge",     "testament": "OT", "desc": "Judge who made a tragic vow"},
    "Samson":        {"group": "judge",     "testament": "OT", "desc": "Judge of supernatural strength"},
    "Delilah":       {"group": "other",     "testament": "OT", "desc": "Philistine woman who betrayed Samson"},
    "Eli":           {"group": "priest",    "testament": "OT", "desc": "Priest of Shiloh, raised Samuel"},
    "Samuel":        {"group": "prophet",   "testament": "OT", "desc": "Last judge, first of the great prophets"},
    "Ruth":          {"group": "matriarch", "testament": "OT", "desc": "Moabite woman, ancestor of David"},
    "Naomi":         {"group": "matriarch", "testament": "OT", "desc": "Mother-in-law of Ruth"},
    "Boaz":          {"group": "other",     "testament": "OT", "desc": "Kinsman-redeemer, husband of Ruth"},
    "Elimelech":     {"group": "other",     "testament": "OT", "desc": "Husband of Naomi, died in Moab"},
    # ═══════════════════════════════════════════════════════════════
    #  UNITED MONARCHY — Saul, David, Solomon
    # ═══════════════════════════════════════════════════════════════
    "Saul":          {"group": "king",      "testament": "OT", "desc": "First king of Israel"},
    "Jonathan":      {"group": "warrior",   "testament": "OT", "desc": "Son of Saul, loyal friend of David"},
    "Michal":        {"group": "queen",     "testament": "OT", "desc": "Daughter of Saul, first wife of David"},
    "Abner":         {"group": "warrior",   "testament": "OT", "desc": "Commander of Saul's army"},
    "Jesse":         {"group": "other",     "testament": "OT", "desc": "Father of David"},
    "David":         {"group": "king",      "testament": "OT", "desc": "Greatest king of Israel, psalmist"},
    "Goliath":       {"group": "warrior",   "testament": "OT", "desc": "Philistine giant slain by David"},
    "Abigail":       {"group": "matriarch", "testament": "OT", "desc": "Wise woman, became wife of David"},
    "Bathsheba":     {"group": "queen",     "testament": "OT", "desc": "Wife of David, mother of Solomon"},
    "Uriah":         {"group": "warrior",   "testament": "OT", "desc": "Hittite husband of Bathsheba, killed by David's order"},
    "Absalom":       {"group": "other",     "testament": "OT", "desc": "Son of David who led a rebellion"},
    "Amnon":         {"group": "other",     "testament": "OT", "desc": "Firstborn of David, assaulted Tamar"},
    "Tamar daughter of David": {"group": "other", "testament": "OT", "desc": "Daughter of David, wronged by Amnon"},
    "Joab":          {"group": "warrior",   "testament": "OT", "desc": "Commander of David's army"},
    "Mephibosheth":  {"group": "other",     "testament": "OT", "desc": "Lame son of Jonathan, protected by David"},
    "Nathan":        {"group": "prophet",   "testament": "OT", "desc": "Prophet who confronted David"},
    "Hushai":        {"group": "other",     "testament": "OT", "desc": "David's friend who thwarted Absalom's counsel"},
    "Ahithophel":    {"group": "other",     "testament": "OT", "desc": "Brilliant counselor who sided with Absalom"},
    "Shimei":        {"group": "other",     "testament": "OT", "desc": "Cursed David during Absalom's revolt"},
    "Zadok":         {"group": "priest",    "testament": "OT", "desc": "Faithful priest under David and Solomon"},
    "Adonijah":      {"group": "other",     "testament": "OT", "desc": "Son of David who tried to seize throne"},
    "Solomon":       {"group": "king",      "testament": "OT", "desc": "Wisest king, built the Temple"},
    "Queen of Sheba": {"group": "queen",    "testament": "OT", "desc": "Visited Solomon to test his wisdom"},
    # ═══════════════════════════════════════════════════════════════
    #  DIVIDED MONARCHY — Kings of Israel (North)
    # ═══════════════════════════════════════════════════════════════
    "Jeroboam I":    {"group": "king",      "testament": "OT", "desc": "First king of northern Israel, set up golden calves"},
    "Nadab of Israel": {"group": "king",    "testament": "OT", "desc": "King of Israel, son of Jeroboam I"},
    "Baasha":        {"group": "king",      "testament": "OT", "desc": "King of Israel, overthrew Nadab"},
    "Elah":          {"group": "king",      "testament": "OT", "desc": "King of Israel, assassinated by Zimri"},
    "Zimri":         {"group": "king",      "testament": "OT", "desc": "King of Israel for 7 days"},
    "Omri":          {"group": "king",      "testament": "OT", "desc": "King of Israel, founded Samaria"},
    "Ahab":          {"group": "king",      "testament": "OT", "desc": "Wicked king of Israel, husband of Jezebel"},
    "Ahaziah of Israel": {"group": "king",  "testament": "OT", "desc": "King of Israel, son of Ahab"},
    "Joram of Israel": {"group": "king",    "testament": "OT", "desc": "King of Israel, son of Ahab"},
    "Jehu":          {"group": "king",      "testament": "OT", "desc": "King of Israel, anointed to destroy house of Ahab"},
    "Jehoahaz of Israel": {"group": "king", "testament": "OT", "desc": "King of Israel, son of Jehu"},
    "Jehoash of Israel": {"group": "king",  "testament": "OT", "desc": "King of Israel, grandson of Jehu"},
    "Jeroboam II":   {"group": "king",      "testament": "OT", "desc": "King of Israel, expanded territory"},
    "Zechariah of Israel": {"group": "king","testament": "OT", "desc": "King of Israel, last of Jehu's dynasty"},
    "Shallum":       {"group": "king",      "testament": "OT", "desc": "King of Israel, reigned one month"},
    "Menahem":       {"group": "king",      "testament": "OT", "desc": "King of Israel, brutal usurper"},
    "Pekahiah":      {"group": "king",      "testament": "OT", "desc": "King of Israel, son of Menahem"},
    "Pekah":         {"group": "king",      "testament": "OT", "desc": "King of Israel, overthrew Pekahiah"},
    "Hoshea":        {"group": "king",      "testament": "OT", "desc": "Last king of Israel before Assyrian exile"},
    # ═══════════════════════════════════════════════════════════════
    #  DIVIDED MONARCHY — Kings of Judah (South)
    # ═══════════════════════════════════════════════════════════════
    "Rehoboam":      {"group": "king",      "testament": "OT", "desc": "Son of Solomon, kingdom divided under him"},
    "Abijah":        {"group": "king",      "testament": "OT", "desc": "King of Judah, son of Rehoboam"},
    "Asa":           {"group": "king",      "testament": "OT", "desc": "Good king of Judah, religious reformer"},
    "Jehoshaphat":   {"group": "king",      "testament": "OT", "desc": "Good king of Judah, strengthened the law"},
    "Jehoram of Judah": {"group": "king",   "testament": "OT", "desc": "Wicked king of Judah"},
    "Ahaziah of Judah": {"group": "king",   "testament": "OT", "desc": "King of Judah killed by Jehu"},
    "Athaliah":      {"group": "queen",     "testament": "OT", "desc": "Queen of Judah, usurped the throne"},
    "Joash of Judah": {"group": "king",     "testament": "OT", "desc": "Boy king, restored the Temple"},
    "Amaziah":       {"group": "king",      "testament": "OT", "desc": "King of Judah, defeated Edom"},
    "Uzziah":        {"group": "king",      "testament": "OT", "desc": "King of Judah, struck with leprosy"},
    "Jotham":        {"group": "king",      "testament": "OT", "desc": "Good king of Judah, son of Uzziah"},
    "Ahaz":          {"group": "king",      "testament": "OT", "desc": "Wicked king of Judah, worshipped idols"},
    "Hezekiah":      {"group": "king",      "testament": "OT", "desc": "Righteous king of Judah, trusted God against Assyria"},
    "Manasseh of Judah": {"group": "king",  "testament": "OT", "desc": "Wicked king of Judah who repented"},
    "Amon":          {"group": "king",      "testament": "OT", "desc": "Wicked king of Judah, son of Manasseh"},
    "Josiah":        {"group": "king",      "testament": "OT", "desc": "Great reformer king, found the Book of the Law"},
    "Jehoahaz of Judah": {"group": "king",  "testament": "OT", "desc": "King of Judah, deposed by Egypt"},
    "Jehoiakim":     {"group": "king",      "testament": "OT", "desc": "King of Judah, burned Jeremiah's scroll"},
    "Jehoiachin":    {"group": "king",      "testament": "OT", "desc": "King of Judah, exiled to Babylon"},
    "Zedekiah":      {"group": "king",      "testament": "OT", "desc": "Last king of Judah before destruction"},
    # ═══════════════════════════════════════════════════════════════
    #  OTHER OT ROYALTY & FOREIGN RULERS
    # ═══════════════════════════════════════════════════════════════
    "Jezebel":       {"group": "queen",     "testament": "OT", "desc": "Wicked Phoenician queen, wife of Ahab"},
    "Naaman":        {"group": "warrior",   "testament": "OT", "desc": "Syrian commander healed of leprosy by Elisha"},
    "Ben-Hadad":     {"group": "king",      "testament": "OT", "desc": "King of Aram (Syria)"},
    "Sennacherib":   {"group": "king",      "testament": "OT", "desc": "Assyrian king who besieged Jerusalem"},
    "Nebuchadnezzar": {"group": "king",     "testament": "OT", "desc": "King of Babylon, destroyed Jerusalem"},
    "Belshazzar":    {"group": "king",      "testament": "OT", "desc": "Last Babylonian king, saw writing on the wall"},
    "Darius":        {"group": "king",      "testament": "OT", "desc": "Medo-Persian king, Daniel in lions' den"},
    "Cyrus":         {"group": "king",      "testament": "OT", "desc": "Persian king who freed the Jews"},
    "Ahasuerus":     {"group": "king",      "testament": "OT", "desc": "Persian king, husband of Esther"},
    # ═══════════════════════════════════════════════════════════════
    #  PROPHETS — Major
    # ═══════════════════════════════════════════════════════════════
    "Elijah":        {"group": "prophet",   "testament": "OT", "desc": "Prophet who challenged Baal on Carmel"},
    "Elisha":        {"group": "prophet",   "testament": "OT", "desc": "Successor of Elijah, performed many miracles"},
    "Isaiah":        {"group": "prophet",   "testament": "OT", "desc": "Major prophet, messianic prophecies"},
    "Jeremiah":      {"group": "prophet",   "testament": "OT", "desc": "Weeping prophet of Judah's last days"},
    "Baruch":        {"group": "other",     "testament": "OT", "desc": "Scribe and companion of Jeremiah"},
    "Ezekiel":       {"group": "prophet",   "testament": "OT", "desc": "Prophet of the exile, visions of God's glory"},
    "Daniel":        {"group": "prophet",   "testament": "OT", "desc": "Prophet in Babylon, interpreter of dreams"},
    # ═══════════════════════════════════════════════════════════════
    #  PROPHETS — Minor (Book of the Twelve)
    # ═══════════════════════════════════════════════════════════════
    "Hosea":         {"group": "prophet",   "testament": "OT", "desc": "Prophet of God's faithful love"},
    "Joel":          {"group": "prophet",   "testament": "OT", "desc": "Prophet of the Day of the Lord"},
    "Amos":          {"group": "prophet",   "testament": "OT", "desc": "Shepherd-prophet of social justice"},
    "Obadiah":       {"group": "prophet",   "testament": "OT", "desc": "Prophet against Edom"},
    "Jonah":         {"group": "prophet",   "testament": "OT", "desc": "Prophet swallowed by a great fish"},
    "Micah":         {"group": "prophet",   "testament": "OT", "desc": "Prophet who foretold the Messiah from Bethlehem"},
    "Nahum":         {"group": "prophet",   "testament": "OT", "desc": "Prophet against Nineveh"},
    "Habakkuk":      {"group": "prophet",   "testament": "OT", "desc": "Prophet who questioned God's justice"},
    "Zephaniah":     {"group": "prophet",   "testament": "OT", "desc": "Prophet of the Day of the Lord"},
    "Haggai":        {"group": "prophet",   "testament": "OT", "desc": "Prophet who urged rebuilding the Temple"},
    "Zechariah":     {"group": "prophet",   "testament": "OT", "desc": "Prophet of messianic visions"},
    "Malachi":       {"group": "prophet",   "testament": "OT", "desc": "Last OT prophet, messenger of the covenant"},
    # ═══════════════════════════════════════════════════════════════
    #  OTHER OT PROPHETS
    # ═══════════════════════════════════════════════════════════════
    "Gad the prophet": {"group": "prophet", "testament": "OT", "desc": "David's seer"},
    "Ahijah":        {"group": "prophet",   "testament": "OT", "desc": "Prophet who foretold the divided kingdom"},
    "Micaiah":       {"group": "prophet",   "testament": "OT", "desc": "Prophet who opposed Ahab"},
    "Huldah":        {"group": "prophet",   "testament": "OT", "desc": "Prophetess consulted by Josiah"},
    # ═══════════════════════════════════════════════════════════════
    #  EXILE & RETURN
    # ═══════════════════════════════════════════════════════════════
    "Shadrach":      {"group": "other",     "testament": "OT", "desc": "Companion of Daniel, survived the furnace"},
    "Meshach":       {"group": "other",     "testament": "OT", "desc": "Companion of Daniel, survived the furnace"},
    "Abednego":      {"group": "other",     "testament": "OT", "desc": "Companion of Daniel, survived the furnace"},
    "Ezra":          {"group": "priest",    "testament": "OT", "desc": "Scribe-priest who led return from exile"},
    "Nehemiah":      {"group": "leader",    "testament": "OT", "desc": "Rebuilt the walls of Jerusalem"},
    "Zerubbabel":    {"group": "leader",    "testament": "OT", "desc": "Led first return from exile, rebuilt Temple"},
    "Esther":        {"group": "queen",     "testament": "OT", "desc": "Jewish queen who saved her people from genocide"},
    "Mordecai":      {"group": "other",     "testament": "OT", "desc": "Cousin of Esther, foiled assassination plot"},
    "Haman":         {"group": "other",     "testament": "OT", "desc": "Villain who plotted to destroy the Jews"},
    "Vashti":        {"group": "queen",     "testament": "OT", "desc": "Queen deposed before Esther"},
    # ═══════════════════════════════════════════════════════════════
    #  WISDOM & POETRY
    # ═══════════════════════════════════════════════════════════════
    "Job":           {"group": "other",     "testament": "OT", "desc": "Righteous sufferer who questioned God"},
    "Eliphaz":       {"group": "other",     "testament": "OT", "desc": "Friend of Job from Teman"},
    "Bildad":        {"group": "other",     "testament": "OT", "desc": "Friend of Job from Shuah"},
    "Zophar":        {"group": "other",     "testament": "OT", "desc": "Friend of Job from Naamah"},
    "Elihu":         {"group": "other",     "testament": "OT", "desc": "Young man who spoke to Job last"},
    # ═══════════════════════════════════════════════════════════════
    #  DEUTEROCANONICAL / Catholic canon
    # ═══════════════════════════════════════════════════════════════
    "Tobit":         {"group": "other",     "testament": "OT", "desc": "Righteous Israelite in exile, went blind"},
    "Tobias":        {"group": "other",     "testament": "OT", "desc": "Son of Tobit, journeyed with Raphael"},
    "Sarah of Tobit": {"group": "other",    "testament": "OT", "desc": "Wife of Tobias, freed from demon"},
    "Judith":        {"group": "other",     "testament": "OT", "desc": "Heroine who beheaded Holofernes"},
    "Holofernes":    {"group": "warrior",   "testament": "OT", "desc": "Assyrian general killed by Judith"},
    "Judas Maccabeus": {"group": "warrior", "testament": "OT", "desc": "Led revolt against Seleucids, rededicated Temple"},
    "Mattathias":    {"group": "priest",    "testament": "OT", "desc": "Father of the Maccabees, started revolt"},
    "Antiochus IV":  {"group": "king",      "testament": "OT", "desc": "Seleucid king who desecrated the Temple"},
    "Eleazar Maccabeus": {"group": "warrior","testament": "OT","desc": "Brother of Judas Maccabeus, died in battle"},
    "Susanna":       {"group": "other",     "testament": "OT", "desc": "Virtuous woman vindicated by Daniel"},
    # ═══════════════════════════════════════════════════════════════
    #  ANGELS
    # ═══════════════════════════════════════════════════════════════
    "Michael":       {"group": "angel",     "testament": "OT", "desc": "Archangel, protector of Israel"},
    "Gabriel":       {"group": "angel",     "testament": "OT", "desc": "Archangel, messenger of God"},
    "Raphael":       {"group": "angel",     "testament": "OT", "desc": "Archangel, healer, guided Tobias"},
    # ═══════════════════════════════════════════════════════════════
    #  DEMONS & ADVERSARIES
    # ═══════════════════════════════════════════════════════════════
    "Satan":         {"group": "demon",     "testament": "OT", "desc": "The adversary, accuser, tempter"},
    "Asmodeus":      {"group": "demon",     "testament": "OT", "desc": "Demon who afflicted Sarah (Tobit)"},
    "Beelzebub":     {"group": "demon",     "testament": "NT", "desc": "Prince of demons"},
    "Legion":        {"group": "demon",     "testament": "NT", "desc": "Many demons cast out by Jesus into swine"},
    # ═══════════════════════════════════════════════════════════════
    #  NEW TESTAMENT — Birth & early life of Jesus
    # ═══════════════════════════════════════════════════════════════
    "Mary":          {"group": "matriarch", "testament": "NT", "desc": "Mother of Jesus, Blessed Virgin"},
    "Joseph of Nazareth": {"group": "other","testament": "NT", "desc": "Earthly father of Jesus, carpenter"},
    "Elizabeth":     {"group": "matriarch", "testament": "NT", "desc": "Mother of John the Baptist"},
    "Zechariah the priest": {"group": "priest","testament": "NT","desc": "Father of John the Baptist"},
    "John the Baptist": {"group": "prophet","testament": "NT", "desc": "Forerunner of Jesus, baptiser"},
    "Jesus":         {"group": "other",     "testament": "NT", "desc": "Central figure, Son of God, the Messiah"},
    "Anna the prophetess": {"group": "prophet","testament": "NT","desc": "Prophetess at the Temple, recognized infant Jesus"},
    "Simeon":        {"group": "other",     "testament": "NT", "desc": "Devout man who blessed the infant Jesus"},
    "Herod the Great": {"group": "king",    "testament": "NT", "desc": "King of Judea at Jesus' birth, ordered massacre"},
    # ═══════════════════════════════════════════════════════════════
    #  THE TWELVE APOSTLES
    # ═══════════════════════════════════════════════════════════════
    "Peter":         {"group": "apostle",   "testament": "NT", "desc": "Leader of the Apostles, the Rock"},
    "Andrew":        {"group": "apostle",   "testament": "NT", "desc": "Brother of Peter, first called"},
    "James son of Zebedee": {"group": "apostle","testament": "NT","desc": "Apostle, first martyred among the Twelve"},
    "John":          {"group": "apostle",   "testament": "NT", "desc": "Beloved disciple, author of Gospel and Revelation"},
    "Philip":        {"group": "apostle",   "testament": "NT", "desc": "Apostle from Bethsaida"},
    "Bartholomew":   {"group": "apostle",   "testament": "NT", "desc": "Apostle, also called Nathanael"},
    "Matthew":       {"group": "apostle",   "testament": "NT", "desc": "Tax collector turned apostle, Gospel writer"},
    "Thomas":        {"group": "apostle",   "testament": "NT", "desc": "Doubting apostle who professed faith"},
    "James son of Alphaeus": {"group": "apostle","testament": "NT","desc": "One of the Twelve"},
    "Thaddaeus":     {"group": "apostle",   "testament": "NT", "desc": "Also called Judas son of James"},
    "Simon the Zealot": {"group": "apostle","testament": "NT", "desc": "Apostle, former zealot"},
    "Judas Iscariot": {"group": "apostle",  "testament": "NT", "desc": "Betrayer of Jesus for 30 silver coins"},
    "Matthias":      {"group": "apostle",   "testament": "NT", "desc": "Replaced Judas Iscariot among the Twelve"},
    # ═══════════════════════════════════════════════════════════════
    #  NT — Other followers & characters in the Gospels
    # ═══════════════════════════════════════════════════════════════
    "Mary Magdalene": {"group": "other",    "testament": "NT", "desc": "Devoted follower, first witness of resurrection"},
    "Martha":        {"group": "other",     "testament": "NT", "desc": "Sister of Lazarus and Mary of Bethany"},
    "Lazarus":       {"group": "other",     "testament": "NT", "desc": "Raised from the dead by Jesus"},
    "Mary of Bethany": {"group": "other",   "testament": "NT", "desc": "Sister of Martha and Lazarus"},
    "Nicodemus":     {"group": "other",     "testament": "NT", "desc": "Pharisee who visited Jesus at night"},
    "Joseph of Arimathea": {"group": "other","testament": "NT","desc": "Provided his tomb for Jesus' burial"},
    "Zacchaeus":     {"group": "other",     "testament": "NT", "desc": "Short tax collector who climbed a tree"},
    "Cleopas":       {"group": "other",     "testament": "NT", "desc": "Disciple on the road to Emmaus"},
    "Jairus":        {"group": "other",     "testament": "NT", "desc": "Synagogue leader whose daughter Jesus raised"},
    "Barabbas":      {"group": "other",     "testament": "NT", "desc": "Prisoner released instead of Jesus"},
    "Simon of Cyrene": {"group": "other",   "testament": "NT", "desc": "Carried the cross of Jesus"},
    "Salome":        {"group": "other",     "testament": "NT", "desc": "Mother of James and John (Zebedee)"},
    "Herodias":      {"group": "other",     "testament": "NT", "desc": "Wife of Herod Antipas, plotted Baptist's death"},
    "Herod Antipas":  {"group": "king",     "testament": "NT", "desc": "Tetrarch who executed John the Baptist"},
    "Salome daughter of Herodias": {"group": "other","testament": "NT","desc": "Danced for Herod, asked for Baptist's head"},
    # ═══════════════════════════════════════════════════════════════
    #  NT — Passion
    # ═══════════════════════════════════════════════════════════════
    "Pontius Pilate": {"group": "other",    "testament": "NT", "desc": "Roman governor who condemned Jesus"},
    "Caiaphas":      {"group": "priest",    "testament": "NT", "desc": "High priest who presided over Jesus' trial"},
    "Annas":         {"group": "priest",    "testament": "NT", "desc": "Former high priest, father-in-law of Caiaphas"},
    # ═══════════════════════════════════════════════════════════════
    #  NT — Acts & Early Church
    # ═══════════════════════════════════════════════════════════════
    "Paul":          {"group": "apostle",   "testament": "NT", "desc": "Apostle to the Gentiles, wrote many epistles"},
    "Barnabas":      {"group": "apostle",   "testament": "NT", "desc": "Companion of Paul on first journey"},
    "James the Just": {"group": "apostle",  "testament": "NT", "desc": "Brother of Jesus, leader of Jerusalem church"},
    "Stephen":       {"group": "other",     "testament": "NT", "desc": "First Christian martyr, stoned to death"},
    "Philip the Evangelist": {"group": "evangelist","testament": "NT","desc": "Deacon, evangelised Samaria and the Ethiopian"},
    "Ananias of Damascus": {"group": "other","testament": "NT","desc": "Disciple who restored Paul's sight"},
    "Ananias":       {"group": "other",     "testament": "NT", "desc": "Lied about property, struck dead"},
    "Sapphira":      {"group": "other",     "testament": "NT", "desc": "Wife of Ananias, also struck dead"},
    "Cornelius":     {"group": "other",     "testament": "NT", "desc": "First Gentile convert, Roman centurion"},
    "Dorcas":        {"group": "other",     "testament": "NT", "desc": "Also called Tabitha, raised by Peter"},
    "Lydia":         {"group": "other",     "testament": "NT", "desc": "Purple-cloth dealer, first European convert"},
    "Silas":         {"group": "other",     "testament": "NT", "desc": "Companion of Paul, imprisoned in Philippi"},
    "Timothy":       {"group": "other",     "testament": "NT", "desc": "Young disciple and companion of Paul"},
    "Titus":         {"group": "other",     "testament": "NT", "desc": "Companion of Paul, leader in Crete"},
    "Luke":          {"group": "evangelist","testament": "NT", "desc": "Physician, author of Gospel and Acts"},
    "Mark":          {"group": "evangelist","testament": "NT", "desc": "Author of earliest Gospel"},
    "Priscilla":     {"group": "other",     "testament": "NT", "desc": "Early church leader, co-worker with Paul"},
    "Aquila":        {"group": "other",     "testament": "NT", "desc": "Husband of Priscilla, tentmaker with Paul"},
    "Apollos":       {"group": "other",     "testament": "NT", "desc": "Eloquent preacher from Alexandria"},
    "Gamaliel":      {"group": "other",     "testament": "NT", "desc": "Pharisee teacher of Paul, counselled tolerance"},
    "Agabus":        {"group": "prophet",   "testament": "NT", "desc": "NT prophet who predicted famine and Paul's arrest"},
    "Rhoda":         {"group": "other",     "testament": "NT", "desc": "Servant girl who answered the door for Peter"},
    "Onesimus":      {"group": "other",     "testament": "NT", "desc": "Runaway slave, subject of Philemon"},
    "Philemon":      {"group": "other",     "testament": "NT", "desc": "Master of Onesimus, Paul's letter recipient"},
    # ═══════════════════════════════════════════════════════════════
    #  NT — Roman officials
    # ═══════════════════════════════════════════════════════════════
    "Felix":         {"group": "other",     "testament": "NT", "desc": "Roman governor who kept Paul in prison"},
    "Festus":        {"group": "other",     "testament": "NT", "desc": "Successor of Felix, sent Paul to Rome"},
    "Agrippa":       {"group": "king",      "testament": "NT", "desc": "King who heard Paul's defence"},
    "Bernice":       {"group": "queen",     "testament": "NT", "desc": "Sister of Agrippa, present at Paul's trial"},
    # ═══════════════════════════════════════════════════════════════
    #  MISC OT figures
    # ═══════════════════════════════════════════════════════════════
    "Gehazi":        {"group": "other",     "testament": "OT", "desc": "Servant of Elisha, struck with leprosy"},
    "Gomer":         {"group": "other",     "testament": "OT", "desc": "Unfaithful wife of the prophet Hosea"},
    "Witch of Endor": {"group": "other",    "testament": "OT", "desc": "Medium consulted by Saul"},
    "Doeg":          {"group": "other",     "testament": "OT", "desc": "Edomite who slaughtered the priests of Nob"},
    "Hiram":         {"group": "king",      "testament": "OT", "desc": "King of Tyre, allied with David and Solomon"},
    # ═══════════════════════════════════════════════════════════════
    #  SPOUSES — named where Bible names them, otherwise "X's wife"
    # ═══════════════════════════════════════════════════════════════
    # Named spouses missing from main list
    "Elisheba":      {"group": "matriarch", "testament": "OT", "desc": "Wife of Aaron, mother of his sons"},
    "Ahinoam":       {"group": "matriarch", "testament": "OT", "desc": "Wife of Saul"},
    "Naamah":        {"group": "queen",     "testament": "OT", "desc": "Ammonite wife of Solomon, mother of Rehoboam"},
    "Zebedee":       {"group": "other",     "testament": "NT", "desc": "Father of James and John, husband of Salome"},
    "Anna wife of Tobit": {"group": "matriarch","testament": "OT","desc": "Wife of Tobit, mother of Tobias"},
    # Unnamed but narratively present
    "Noah's wife":   {"group": "matriarch", "testament": "OT", "desc": "Wife of Noah, survived the Flood"},
    "Lot's wife":    {"group": "other",     "testament": "OT", "desc": "Turned into a pillar of salt fleeing Sodom"},
    "Potiphar's wife": {"group": "other",   "testament": "OT", "desc": "Falsely accused Joseph"},
    "Lamech's wife": {"group": "matriarch", "testament": "OT", "desc": "Wife of Lamech, mother of Noah"},
    "Methuselah's wife": {"group": "matriarch","testament": "OT","desc": "Wife of Methuselah"},
    "Enoch's wife":  {"group": "matriarch", "testament": "OT", "desc": "Wife of Enoch"},
    "Terah's wife":  {"group": "matriarch", "testament": "OT", "desc": "Wife of Terah, mother of Abraham"},
    "Laban's wife":  {"group": "matriarch", "testament": "OT", "desc": "Wife of Laban, mother of Leah and Rachel"},
    "Jesse's wife":  {"group": "matriarch", "testament": "OT", "desc": "Wife of Jesse, mother of David"},
    "Jonathan's wife": {"group": "matriarch","testament": "OT", "desc": "Wife of Jonathan, mother of Mephibosheth"},
    "Gideon's concubine": {"group": "other","testament": "OT", "desc": "Mother of Abimelech"},
    "Jethro's wife": {"group": "matriarch", "testament": "OT", "desc": "Wife of Jethro"},
    # King succession wives (Judah)
    "Rehoboam's wife": {"group": "queen",   "testament": "OT", "desc": "Wife of Rehoboam"},
    "Abijah's wife": {"group": "queen",     "testament": "OT", "desc": "Wife of Abijah"},
    "Asa's wife":    {"group": "queen",     "testament": "OT", "desc": "Wife of Asa"},
    "Jehoshaphat's wife": {"group": "queen","testament": "OT", "desc": "Wife of Jehoshaphat"},
    "Jehoram's wife": {"group": "queen",    "testament": "OT", "desc": "Wife of Jehoram of Judah"},
    "Ahaziah's wife": {"group": "queen",    "testament": "OT", "desc": "Wife of Ahaziah of Judah"},
    "Joash's wife":  {"group": "queen",     "testament": "OT", "desc": "Wife of Joash of Judah"},
    "Amaziah's wife": {"group": "queen",    "testament": "OT", "desc": "Wife of Amaziah"},
    "Uzziah's wife": {"group": "queen",     "testament": "OT", "desc": "Wife of Uzziah"},
    "Jotham's wife": {"group": "queen",     "testament": "OT", "desc": "Wife of Jotham"},
    "Ahaz's wife":   {"group": "queen",     "testament": "OT", "desc": "Wife of Ahaz"},
    "Hezekiah's wife": {"group": "queen",   "testament": "OT", "desc": "Wife of Hezekiah"},
    "Manasseh's wife": {"group": "queen",   "testament": "OT", "desc": "Wife of Manasseh of Judah"},
    "Amon's wife":   {"group": "queen",     "testament": "OT", "desc": "Wife of Amon"},
    "Josiah's wife": {"group": "queen",     "testament": "OT", "desc": "Wife of Josiah"},
    "Jehoiakim's wife": {"group": "queen",  "testament": "OT", "desc": "Wife of Jehoiakim"},
    # King succession wives (Israel)
    "Jeroboam's wife": {"group": "queen",   "testament": "OT", "desc": "Wife of Jeroboam I"},
    "Baasha's wife": {"group": "queen",     "testament": "OT", "desc": "Wife of Baasha"},
    "Omri's wife":   {"group": "queen",     "testament": "OT", "desc": "Wife of Omri"},
    "Jehu's wife":   {"group": "queen",     "testament": "OT", "desc": "Wife of Jehu"},
    "Jehoahaz's wife": {"group": "queen",   "testament": "OT", "desc": "Wife of Jehoahaz of Israel"},
    "Jehoash's wife": {"group": "queen",    "testament": "OT", "desc": "Wife of Jehoash of Israel"},
    "Jeroboam II's wife": {"group": "queen","testament": "OT", "desc": "Wife of Jeroboam II"},
    "Menahem's wife": {"group": "queen",    "testament": "OT", "desc": "Wife of Menahem"},
    # Other
    "Mattathias's wife": {"group": "matriarch","testament": "OT","desc": "Wife of Mattathias, mother of the Maccabees"},
    "Eleazar's wife": {"group": "matriarch", "testament": "OT", "desc": "Wife of Eleazar, mother of Phinehas"},
}

# ═══════════════════════════════════════════════════════════════════
#  RELATIONSHIPS
# ═══════════════════════════════════════════════════════════════════
RELATIONSHIPS = [
    # ── Genesis primeval ──
    ("Adam", "Eve", "spouse"),
    ("Adam", "Cain", "parent"),
    ("Adam", "Abel", "parent"),
    ("Adam", "Seth", "parent"),
    ("Eve", "Cain", "parent"),
    ("Eve", "Abel", "parent"),
    ("Eve", "Seth", "parent"),
    ("Cain", "Abel", "killed"),
    # Sethite line (Gen 5)
    ("Seth", "Enosh", "parent"),
    ("Enosh", "Kenan", "parent"),
    ("Kenan", "Mahalalel", "parent"),
    ("Mahalalel", "Jared", "parent"),
    ("Jared", "Enoch", "parent"),
    ("Enoch", "Methuselah", "parent"),
    ("Methuselah", "Lamech", "parent"),
    ("Lamech", "Noah", "parent"),
    ("Noah", "Shem", "parent"),
    ("Noah", "Ham", "parent"),
    ("Noah", "Japheth", "parent"),
    # Table of Nations — sons of Japheth (Gen 10:2)
    ("Japheth", "Gomer", "parent"),
    ("Japheth", "Magog", "parent"),
    ("Japheth", "Madai", "parent"),
    ("Japheth", "Javan", "parent"),
    ("Japheth", "Tubal", "parent"),
    ("Japheth", "Meshech", "parent"),
    ("Japheth", "Tiras", "parent"),
    # Table of Nations — sons of Ham (Gen 10:6)
    ("Ham", "Cush", "parent"),
    ("Ham", "Mizraim", "parent"),
    ("Ham", "Put", "parent"),
    ("Ham", "Canaan", "parent"),
    ("Cush", "Nimrod", "parent"),
    # Table of Nations — sons of Shem (Gen 10:22)
    ("Shem", "Elam", "parent"),
    ("Shem", "Asshur", "parent"),
    ("Shem", "Arphaxad", "parent"),
    ("Shem", "Lud", "parent"),
    ("Shem", "Aram", "parent"),
    ("Satan", "Eve", "tempted"),
    ("Satan", "Adam", "tempted"),
    # ── Patriarchs ──
    # Shem → Terah bridge (Gen 11:10-26)
    ("Arphaxad", "Shelah", "parent"),
    ("Shelah", "Eber", "parent"),
    ("Eber", "Peleg", "parent"),
    ("Peleg", "Reu", "parent"),
    ("Reu", "Serug", "parent"),
    ("Serug", "Nahor son of Serug", "parent"),
    ("Nahor son of Serug", "Terah", "parent"),
    ("Terah", "Abraham", "parent"),
    ("Abraham", "Lot", "uncle"),
    ("Abraham", "Sarah", "spouse"),
    ("Abraham", "Hagar", "relationship"),
    ("Abraham", "Isaac", "parent"),
    ("Abraham", "Ishmael", "parent"),
    ("Hagar", "Ishmael", "parent"),
    ("Sarah", "Isaac", "parent"),
    ("Abraham", "Melchizedek", "blessed by"),
    ("Isaac", "Rebekah", "spouse"),
    ("Rebekah", "Laban", "sibling"),
    ("Isaac", "Jacob", "parent"),
    ("Isaac", "Esau", "parent"),
    ("Rebekah", "Jacob", "parent"),
    ("Rebekah", "Esau", "parent"),
    ("Jacob", "Esau", "twin brother"),
    ("Jacob", "Leah", "spouse"),
    ("Jacob", "Rachel", "spouse"),
    ("Laban", "Leah", "parent"),
    ("Laban", "Rachel", "parent"),
    # Jacob's children
    ("Jacob", "Reuben", "parent"),
    ("Leah", "Reuben", "parent"),
    ("Jacob", "Simeon", "parent"),
    ("Leah", "Simeon", "parent"),
    ("Jacob", "Levi", "parent"),
    ("Leah", "Levi", "parent"),
    ("Jacob", "Judah", "parent"),
    ("Leah", "Judah", "parent"),
    ("Jacob", "Dan", "parent"),
    ("Jacob", "Naphtali", "parent"),
    ("Jacob", "Gad", "parent"),
    ("Jacob", "Asher", "parent"),
    ("Jacob", "Issachar", "parent"),
    ("Leah", "Issachar", "parent"),
    ("Jacob", "Zebulun", "parent"),
    ("Leah", "Zebulun", "parent"),
    ("Jacob", "Joseph", "parent"),
    ("Rachel", "Joseph", "parent"),
    ("Jacob", "Benjamin", "parent"),
    ("Rachel", "Benjamin", "parent"),
    ("Jacob", "Dinah", "parent"),
    ("Leah", "Dinah", "parent"),
    # Joseph & Egypt
    ("Judah", "Tamar", "father-in-law"),
    ("Joseph", "Potiphar", "served"),
    ("Joseph", "Asenath", "spouse"),
    ("Joseph", "Ephraim", "parent"),
    ("Joseph", "Manasseh", "parent"),
    ("Asenath", "Ephraim", "parent"),
    ("Asenath", "Manasseh", "parent"),
    ("Joseph", "Benjamin", "sibling"),
    # ── Exodus ──
    ("Levi", "Moses", "ancestor"),
    ("Levi", "Aaron", "ancestor"),
    ("Moses", "Aaron", "sibling"),
    ("Moses", "Miriam", "sibling"),
    ("Aaron", "Miriam", "sibling"),
    ("Moses", "Zipporah", "spouse"),
    ("Jethro", "Zipporah", "parent"),
    ("Jethro", "Moses", "father-in-law"),
    ("Moses", "Pharaoh", "opposed"),
    ("Aaron", "Nadab", "parent"),
    ("Aaron", "Abihu", "parent"),
    ("Aaron", "Eleazar", "parent"),
    ("Aaron", "Phinehas", "ancestor"),
    ("Eleazar", "Phinehas", "parent"),
    ("Moses", "Joshua", "mentor"),
    ("Moses", "Caleb", "sent as spy"),
    ("Joshua", "Caleb", "fellow spy"),
    ("Korah", "Moses", "rebelled against"),
    ("Korah", "Aaron", "rebelled against"),
    ("Balak", "Balaam", "hired"),
    ("Balaam", "Moses", "opposed"),
    ("Moses", "Bezalel", "appointed"),
    # ── Joshua ──
    ("Joshua", "Rahab", "spared"),
    ("Joshua", "Achan", "punished"),
    # ── Judges ──
    ("Othniel", "Caleb", "nephew"),
    ("Deborah", "Barak", "commanded"),
    ("Barak", "Sisera", "defeated"),
    ("Jael", "Sisera", "killed"),
    ("Gideon", "Abimelech", "parent"),
    ("Samson", "Delilah", "betrayed by"),
    ("Eli", "Samuel", "mentor"),
    # Ruth
    ("Elimelech", "Naomi", "spouse"),
    ("Ruth", "Naomi", "daughter-in-law"),
    ("Ruth", "Boaz", "spouse"),
    ("Boaz", "Jesse", "ancestor"),
    # ── United monarchy ──
    ("Samuel", "Saul", "anointed"),
    ("Samuel", "David", "anointed"),
    ("Saul", "Jonathan", "parent"),
    ("Saul", "Michal", "parent"),
    ("Saul", "David", "predecessor"),
    ("Saul", "Witch of Endor", "consulted"),
    ("Jonathan", "David", "friendship"),
    ("David", "Michal", "spouse"),
    ("David", "Goliath", "defeated"),
    ("Jesse", "David", "parent"),
    ("David", "Abigail", "spouse"),
    ("David", "Bathsheba", "spouse"),
    ("David", "Solomon", "parent"),
    ("David", "Absalom", "parent"),
    ("David", "Amnon", "parent"),
    ("David", "Tamar daughter of David", "parent"),
    ("David", "Adonijah", "parent"),
    ("Bathsheba", "Solomon", "parent"),
    ("Uriah", "Bathsheba", "spouse"),
    ("David", "Uriah", "sent to death"),
    ("Absalom", "David", "rebelled against"),
    ("Absalom", "Amnon", "killed"),
    ("Amnon", "Tamar daughter of David", "assaulted"),
    ("Joab", "David", "served"),
    ("Joab", "Absalom", "killed"),
    ("Joab", "Abner", "killed"),
    ("Abner", "Saul", "served"),
    ("Nathan", "David", "confronted"),
    ("David", "Mephibosheth", "protected"),
    ("Jonathan", "Mephibosheth", "parent"),
    ("Hushai", "David", "served"),
    ("Ahithophel", "Absalom", "advised"),
    ("Hushai", "Ahithophel", "outwitted"),
    ("Shimei", "David", "cursed"),
    ("Zadok", "David", "served"),
    ("Zadok", "Solomon", "anointed"),
    ("Nathan", "Solomon", "supported"),
    ("Ruth", "David", "ancestor"),
    ("Judah", "David", "ancestor"),
    ("Gad the prophet", "David", "advised"),
    ("Doeg", "Saul", "served"),
    # Solomon
    ("Solomon", "Queen of Sheba", "visited by"),
    ("Solomon", "Rehoboam", "parent"),
    ("Solomon", "Hiram", "allied with"),
    ("David", "Hiram", "allied with"),
    # ── Northern kings succession ──
    ("Ahijah", "Jeroboam I", "prophesied kingship"),
    ("Rehoboam", "Jeroboam I", "rival"),
    ("Jeroboam I", "Nadab of Israel", "parent"),
    ("Nadab of Israel", "Baasha", "killed by"),
    ("Baasha", "Elah", "parent"),
    ("Elah", "Zimri", "killed by"),
    ("Zimri", "Omri", "overthrown by"),
    ("Omri", "Ahab", "parent"),
    ("Ahab", "Jezebel", "spouse"),
    ("Ahab", "Ahaziah of Israel", "parent"),
    ("Ahab", "Joram of Israel", "parent"),
    ("Jehu", "Joram of Israel", "killed"),
    ("Jehu", "Ahaziah of Judah", "killed"),
    ("Jehu", "Jezebel", "had killed"),
    ("Jehu", "Jehoahaz of Israel", "parent"),
    ("Jehoahaz of Israel", "Jehoash of Israel", "parent"),
    ("Jehoash of Israel", "Jeroboam II", "parent"),
    ("Jeroboam II", "Zechariah of Israel", "parent"),
    ("Zechariah of Israel", "Shallum", "killed by"),
    ("Shallum", "Menahem", "killed by"),
    ("Menahem", "Pekahiah", "parent"),
    ("Pekahiah", "Pekah", "killed by"),
    ("Pekah", "Hoshea", "killed by"),
    # ── Southern kings succession ──
    ("Rehoboam", "Abijah", "parent"),
    ("Abijah", "Asa", "parent"),
    ("Asa", "Jehoshaphat", "parent"),
    ("Jehoshaphat", "Jehoram of Judah", "parent"),
    ("Jehoram of Judah", "Ahaziah of Judah", "parent"),
    ("Ahaziah of Judah", "Athaliah", "parent"),
    ("Athaliah", "Joash of Judah", "usurped"),
    ("Joash of Judah", "Amaziah", "parent"),
    ("Amaziah", "Uzziah", "parent"),
    ("Uzziah", "Jotham", "parent"),
    ("Jotham", "Ahaz", "parent"),
    ("Ahaz", "Hezekiah", "parent"),
    ("Hezekiah", "Manasseh of Judah", "parent"),
    ("Manasseh of Judah", "Amon", "parent"),
    ("Amon", "Josiah", "parent"),
    ("Josiah", "Jehoahaz of Judah", "parent"),
    ("Josiah", "Jehoiakim", "parent"),
    ("Jehoiakim", "Jehoiachin", "parent"),
    ("Josiah", "Zedekiah", "parent"),
    # ── Prophets & kings interaction ──
    ("Elijah", "Ahab", "opposed"),
    ("Elijah", "Jezebel", "opposed"),
    ("Elijah", "Elisha", "mentor"),
    ("Micaiah", "Ahab", "warned"),
    ("Elisha", "Naaman", "healed"),
    ("Elisha", "Gehazi", "master of"),
    ("Gehazi", "Naaman", "deceived"),
    ("Elisha", "Jehu", "anointed"),
    ("Elisha", "Ben-Hadad", "prophesied against"),
    ("Isaiah", "Hezekiah", "advised"),
    ("Isaiah", "Uzziah", "called in reign of"),
    ("Huldah", "Josiah", "consulted by"),
    ("Jeremiah", "Josiah", "contemporary"),
    ("Jeremiah", "Jehoiakim", "opposed"),
    ("Jeremiah", "Zedekiah", "warned"),
    ("Jeremiah", "Baruch", "dictated to"),
    ("Sennacherib", "Hezekiah", "besieged"),
    ("Nebuchadnezzar", "Zedekiah", "conquered"),
    ("Nebuchadnezzar", "Jehoiachin", "exiled"),
    ("Nebuchadnezzar", "Daniel", "ruler over"),
    ("Nebuchadnezzar", "Shadrach", "threw in furnace"),
    ("Nebuchadnezzar", "Meshach", "threw in furnace"),
    ("Nebuchadnezzar", "Abednego", "threw in furnace"),
    ("Shadrach", "Meshach", "companion"),
    ("Meshach", "Abednego", "companion"),
    ("Shadrach", "Daniel", "companion"),
    ("Belshazzar", "Daniel", "consulted"),
    ("Darius", "Daniel", "ruler over"),
    ("Cyrus", "Ezra", "decreed return"),
    ("Cyrus", "Zerubbabel", "decreed return"),
    # Prophets fellow
    ("Hosea", "Gomer", "spouse"),
    ("Amos", "Hosea", "fellow prophet"),
    ("Micah", "Isaiah", "fellow prophet"),
    ("Haggai", "Zechariah", "fellow prophet"),
    ("Haggai", "Zerubbabel", "encouraged"),
    ("Zechariah", "Zerubbabel", "encouraged"),
    # Exile & return
    ("Ezra", "Nehemiah", "co-labourers"),
    ("Esther", "Mordecai", "cousin"),
    ("Esther", "Ahasuerus", "spouse"),
    ("Mordecai", "Haman", "opposed"),
    ("Haman", "Esther", "plotted against"),
    ("Haman", "Mordecai", "plotted against"),
    ("Ahasuerus", "Vashti", "spouse"),
    ("Vashti", "Esther", "predecessor"),
    # Wisdom
    ("Job", "Satan", "afflicted by"),
    ("Job", "Eliphaz", "debated with"),
    ("Job", "Bildad", "debated with"),
    ("Job", "Zophar", "debated with"),
    ("Job", "Elihu", "rebuked by"),
    # Deuterocanonical
    ("Tobit", "Tobias", "parent"),
    ("Tobias", "Sarah of Tobit", "spouse"),
    ("Raphael", "Tobias", "guided"),
    ("Asmodeus", "Sarah of Tobit", "afflicted"),
    ("Raphael", "Asmodeus", "defeated"),
    ("Judith", "Holofernes", "killed"),
    ("Mattathias", "Judas Maccabeus", "parent"),
    ("Mattathias", "Eleazar Maccabeus", "parent"),
    ("Judas Maccabeus", "Antiochus IV", "fought"),
    ("Daniel", "Susanna", "vindicated"),
    # Angels & demons — cross-testament
    ("Gabriel", "Daniel", "appeared to"),
    ("Michael", "Daniel", "appeared to"),
    ("Gabriel", "Mary", "announced to"),
    ("Gabriel", "Zechariah the priest", "announced to"),
    ("Michael", "Satan", "opposed"),
    ("Satan", "Job", "afflicted"),
    ("Satan", "Jesus", "tempted"),
    # ═══════════════════════════════════════════════════════════════
    #  NEW TESTAMENT
    # ═══════════════════════════════════════════════════════════════
    # Birth & family
    ("Zechariah the priest", "Elizabeth", "spouse"),
    ("Zechariah the priest", "John the Baptist", "parent"),
    ("Elizabeth", "John the Baptist", "parent"),
    ("Elizabeth", "Mary", "relative"),
    ("Joseph of Nazareth", "Mary", "spouse"),
    ("Mary", "Jesus", "parent"),
    ("Joseph of Nazareth", "Jesus", "guardian"),
    ("Mary", "James the Just", "parent"),
    ("Jesus", "James the Just", "sibling"),
    ("Anna the prophetess", "Jesus", "recognised"),
    ("Simeon", "Jesus", "blessed"),
    ("Herod the Great", "Jesus", "sought to kill"),
    # John the Baptist
    ("John the Baptist", "Jesus", "baptised"),
    ("Herod Antipas", "John the Baptist", "executed"),
    ("Herodias", "Herod Antipas", "spouse"),
    ("Herodias", "Salome daughter of Herodias", "parent"),
    ("Salome daughter of Herodias", "John the Baptist", "requested death of"),
    # Jesus & apostles
    ("Jesus", "Peter", "called"),
    ("Jesus", "Andrew", "called"),
    ("Jesus", "James son of Zebedee", "called"),
    ("Jesus", "John", "called"),
    ("Jesus", "Philip", "called"),
    ("Jesus", "Bartholomew", "called"),
    ("Jesus", "Matthew", "called"),
    ("Jesus", "Thomas", "called"),
    ("Jesus", "James son of Alphaeus", "called"),
    ("Jesus", "Thaddaeus", "called"),
    ("Jesus", "Simon the Zealot", "called"),
    ("Jesus", "Judas Iscariot", "called"),
    ("Peter", "Andrew", "sibling"),
    ("James son of Zebedee", "John", "sibling"),
    ("Salome", "James son of Zebedee", "parent"),
    ("Salome", "John", "parent"),
    ("Judas Iscariot", "Jesus", "betrayed"),
    ("Matthias", "Judas Iscariot", "replaced"),
    # Jesus & others
    ("Jesus", "Mary Magdalene", "follower"),
    ("Jesus", "Lazarus", "raised"),
    ("Jesus", "Martha", "friend"),
    ("Jesus", "Mary of Bethany", "friend"),
    ("Martha", "Lazarus", "sibling"),
    ("Martha", "Mary of Bethany", "sibling"),
    ("Lazarus", "Mary of Bethany", "sibling"),
    ("Jesus", "Nicodemus", "taught"),
    ("Jesus", "Zacchaeus", "visited"),
    ("Jesus", "Jairus", "healed daughter"),
    ("Jesus", "Legion", "cast out"),
    ("Jesus", "Beelzebub", "accused of using"),
    ("Jesus", "Cleopas", "appeared to"),
    ("Jesus", "Barabbas", "released instead of"),
    ("Simon of Cyrene", "Jesus", "carried cross for"),
    # Passion
    ("Caiaphas", "Jesus", "tried"),
    ("Annas", "Caiaphas", "father-in-law"),
    ("Annas", "Jesus", "questioned"),
    ("Caiaphas", "Pontius Pilate", "handed over to"),
    ("Pontius Pilate", "Jesus", "condemned"),
    ("Joseph of Arimathea", "Jesus", "buried"),
    ("Nicodemus", "Jesus", "helped bury"),
    # Early church — Acts
    ("Jesus", "Paul", "appeared to"),
    ("Stephen", "Paul", "martyred before"),
    ("Paul", "Barnabas", "co-labourers"),
    ("Paul", "Silas", "companion"),
    ("Paul", "Timothy", "mentor"),
    ("Paul", "Titus", "mentor"),
    ("Paul", "Luke", "companion"),
    ("Paul", "Mark", "companion"),
    ("Paul", "Priscilla", "co-labourers"),
    ("Paul", "Aquila", "co-labourers"),
    ("Priscilla", "Aquila", "spouse"),
    ("Priscilla", "Apollos", "taught"),
    ("Aquila", "Apollos", "taught"),
    ("Paul", "Apollos", "co-labourers"),
    ("Peter", "Paul", "co-labourers"),
    ("Peter", "Mark", "companion"),
    ("Peter", "Cornelius", "baptised"),
    ("Peter", "Dorcas", "raised"),
    ("Peter", "Ananias", "confronted"),
    ("Ananias", "Sapphira", "spouse"),
    ("Peter", "Rhoda", "answered by"),
    ("Barnabas", "Mark", "companion"),
    ("Paul", "Gamaliel", "student of"),
    ("Paul", "Ananias of Damascus", "healed by"),
    ("Paul", "Lydia", "converted"),
    ("Paul", "Onesimus", "appealed for"),
    ("Onesimus", "Philemon", "slave of"),
    ("Paul", "Philemon", "wrote to"),
    ("Paul", "Agabus", "warned by"),
    ("James the Just", "Peter", "co-labourers"),
    ("James the Just", "Paul", "co-labourers"),
    ("Philip the Evangelist", "Stephen", "fellow deacon"),
    # Roman officials
    ("Paul", "Felix", "tried before"),
    ("Paul", "Festus", "appealed to"),
    ("Paul", "Agrippa", "testified before"),
    ("Agrippa", "Bernice", "sibling"),
    ("Festus", "Agrippa", "consulted"),
    # Prophecy → fulfilment
    ("Isaiah", "Jesus", "prophesied"),
    ("Micah", "Jesus", "prophesied"),
    ("Daniel", "Jesus", "prophesied"),
    ("Zechariah", "Jesus", "prophesied"),
    ("Malachi", "John the Baptist", "prophesied"),
    ("Jonah", "Jesus", "foreshadowed"),
    ("Melchizedek", "Jesus", "foreshadowed"),
    # Lineage
    ("Abraham", "David", "ancestor"),
    ("David", "Jesus", "ancestor"),
    ("Rahab", "David", "ancestor"),
    ("Tamar", "David", "ancestor"),
    ("Ruth", "David", "ancestor"),
    # ── Spouse & parent edges for added spouses ──
    # Named spouses
    ("Aaron", "Elisheba", "spouse"),
    ("Elisheba", "Nadab", "parent"),
    ("Elisheba", "Abihu", "parent"),
    ("Elisheba", "Eleazar", "parent"),
    ("Saul", "Ahinoam", "spouse"),
    ("Ahinoam", "Jonathan", "parent"),
    ("Ahinoam", "Michal", "parent"),
    ("Solomon", "Naamah", "spouse"),
    ("Naamah", "Rehoboam", "parent"),
    ("Salome", "Zebedee", "spouse"),
    ("Tobit", "Anna wife of Tobit", "spouse"),
    ("Anna wife of Tobit", "Tobias", "parent"),
    # Unnamed but significant
    ("Noah", "Noah's wife", "spouse"),
    ("Noah's wife", "Shem", "parent"),
    ("Noah's wife", "Ham", "parent"),
    ("Noah's wife", "Japheth", "parent"),
    ("Lot", "Lot's wife", "spouse"),
    ("Potiphar", "Potiphar's wife", "spouse"),
    ("Potiphar's wife", "Joseph", "falsely accused"),
    ("Lamech", "Lamech's wife", "spouse"),
    ("Lamech's wife", "Noah", "parent"),
    ("Methuselah", "Methuselah's wife", "spouse"),
    ("Methuselah's wife", "Lamech", "parent"),
    ("Enoch", "Enoch's wife", "spouse"),
    ("Enoch's wife", "Methuselah", "parent"),
    ("Terah", "Terah's wife", "spouse"),
    ("Terah's wife", "Abraham", "parent"),
    ("Laban", "Laban's wife", "spouse"),
    ("Laban's wife", "Leah", "parent"),
    ("Laban's wife", "Rachel", "parent"),
    ("Jesse", "Jesse's wife", "spouse"),
    ("Jesse's wife", "David", "parent"),
    ("Jonathan", "Jonathan's wife", "spouse"),
    ("Jonathan's wife", "Mephibosheth", "parent"),
    ("Gideon", "Gideon's concubine", "relationship"),
    ("Gideon's concubine", "Abimelech", "parent"),
    ("Jethro", "Jethro's wife", "spouse"),
    ("Jethro's wife", "Zipporah", "parent"),
    ("Eleazar", "Eleazar's wife", "spouse"),
    ("Eleazar's wife", "Phinehas", "parent"),
    ("Mattathias", "Mattathias's wife", "spouse"),
    ("Mattathias's wife", "Judas Maccabeus", "parent"),
    ("Mattathias's wife", "Eleazar Maccabeus", "parent"),
    # Kings of Judah wives
    ("Rehoboam", "Rehoboam's wife", "spouse"),
    ("Rehoboam's wife", "Abijah", "parent"),
    ("Abijah", "Abijah's wife", "spouse"),
    ("Abijah's wife", "Asa", "parent"),
    ("Asa", "Asa's wife", "spouse"),
    ("Asa's wife", "Jehoshaphat", "parent"),
    ("Jehoshaphat", "Jehoshaphat's wife", "spouse"),
    ("Jehoshaphat's wife", "Jehoram of Judah", "parent"),
    ("Jehoram of Judah", "Jehoram's wife", "spouse"),
    ("Jehoram's wife", "Ahaziah of Judah", "parent"),
    ("Ahaziah of Judah", "Ahaziah's wife", "spouse"),
    ("Ahaziah's wife", "Athaliah", "parent"),
    ("Joash of Judah", "Joash's wife", "spouse"),
    ("Joash's wife", "Amaziah", "parent"),
    ("Amaziah", "Amaziah's wife", "spouse"),
    ("Amaziah's wife", "Uzziah", "parent"),
    ("Uzziah", "Uzziah's wife", "spouse"),
    ("Uzziah's wife", "Jotham", "parent"),
    ("Jotham", "Jotham's wife", "spouse"),
    ("Jotham's wife", "Ahaz", "parent"),
    ("Ahaz", "Ahaz's wife", "spouse"),
    ("Ahaz's wife", "Hezekiah", "parent"),
    ("Hezekiah", "Hezekiah's wife", "spouse"),
    ("Hezekiah's wife", "Manasseh of Judah", "parent"),
    ("Manasseh of Judah", "Manasseh's wife", "spouse"),
    ("Manasseh's wife", "Amon", "parent"),
    ("Amon", "Amon's wife", "spouse"),
    ("Amon's wife", "Josiah", "parent"),
    ("Josiah", "Josiah's wife", "spouse"),
    ("Josiah's wife", "Jehoahaz of Judah", "parent"),
    ("Josiah's wife", "Jehoiakim", "parent"),
    ("Josiah's wife", "Zedekiah", "parent"),
    ("Jehoiakim", "Jehoiakim's wife", "spouse"),
    ("Jehoiakim's wife", "Jehoiachin", "parent"),
    # Kings of Israel wives
    ("Jeroboam I", "Jeroboam's wife", "spouse"),
    ("Jeroboam's wife", "Nadab of Israel", "parent"),
    ("Baasha", "Baasha's wife", "spouse"),
    ("Baasha's wife", "Elah", "parent"),
    ("Omri", "Omri's wife", "spouse"),
    ("Omri's wife", "Ahab", "parent"),
    ("Jehu", "Jehu's wife", "spouse"),
    ("Jehu's wife", "Jehoahaz of Israel", "parent"),
    ("Jehoahaz of Israel", "Jehoahaz's wife", "spouse"),
    ("Jehoahaz's wife", "Jehoash of Israel", "parent"),
    ("Jehoash of Israel", "Jehoash's wife", "spouse"),
    ("Jehoash's wife", "Jeroboam II", "parent"),
    ("Jeroboam II", "Jeroboam II's wife", "spouse"),
    ("Jeroboam II's wife", "Zechariah of Israel", "parent"),
    ("Menahem", "Menahem's wife", "spouse"),
    ("Menahem's wife", "Pekahiah", "parent"),
]

# Edge colours by relationship type
EDGE_COLOURS = {
    "spouse":           "#E74C3C",
    "parent":           "#2E86C1",
    "sibling":          "#1ABC9C",
    "ancestor":         "#7F8C8D",
    "uncle":            "#7F8C8D",
    "cousin":           "#7F8C8D",
    "relative":         "#7F8C8D",
    "twin brother":     "#1ABC9C",
    "father-in-law":    "#AF7AC5",
    "daughter-in-law":  "#AF7AC5",
    "mother-in-law":    "#AF7AC5",
    "mentor":           "#F39C12",
    "anointed":         "#8E44AD",
    "called":           "#3498DB",
    "betrayed":         "#C0392B",
    "betrayed by":      "#C0392B",
    "killed":           "#C0392B",
    "killed by":        "#C0392B",
    "had killed":       "#C0392B",
    "sent to death":    "#C0392B",
    "defeated":         "#E67E22",
    "opposed":          "#E74C3C",
    "follower":         "#27AE60",
    "prophesied":       "#27AE60",
    "foreshadowed":     "#27AE60",
    "baptised":         "#3498DB",
    "condemned":        "#7F8C8D",
    "tried":            "#C0392B",
    "questioned":       "#C0392B",
    "executed":         "#C0392B",
    "sought to kill":   "#C0392B",
    "requested death of": "#C0392B",
    "relationship":     "#E74C3C",
    "friendship":       "#F39C12",
    "friend":           "#F39C12",
    "predecessor":      "#7F8C8D",
    "rival":            "#E67E22",
    "confronted":       "#E67E22",
    "warned":           "#E67E22",
    "advised":          "#27AE60",
    "encouraged":       "#27AE60",
    "supported":        "#27AE60",
    "contemporary":     "#95A5A6",
    "companion":        "#3498DB",
    "co-labourers":     "#3498DB",
    "served":           "#3498DB",
    "ruler over":       "#F4D03F",
    "sent as spy":      "#F39C12",
    "fellow spy":       "#F39C12",
    "guardian":         "#2E86C1",
    "raised":           "#8E44AD",
    "healed":           "#8E44AD",
    "healed by":        "#8E44AD",
    "associated":       "#95A5A6",
    "handed over to":   "#C0392B",
    "rebelled against": "#C0392B",
    "martyred before":  "#C0392B",
    "tempted":          "#C0392B",
    "afflicted":        "#C0392B",
    "afflicted by":     "#C0392B",
    "cast out":         "#8E44AD",
    "guided":           "#27AE60",
    "appeared to":      "#8E44AD",
    "announced to":     "#8E44AD",
    "recognised":       "#27AE60",
    "blessed":          "#27AE60",
    "blessed by":       "#27AE60",
    "taught":           "#3498DB",
    "visited":          "#3498DB",
    "visited by":       "#3498DB",
    "converted":        "#27AE60",
    "wrote to":         "#3498DB",
    "student of":       "#F39C12",
    "tried before":     "#C0392B",
    "appealed to":      "#C0392B",
    "testified before": "#3498DB",
    "consulted":        "#F39C12",
    "consulted by":     "#F39C12",
    "dictated to":      "#3498DB",
    "appointed":        "#8E44AD",
    "spared":           "#27AE60",
    "punished":         "#C0392B",
    "nephew":           "#7F8C8D",
    "commanded":        "#F39C12",
    "master of":        "#F39C12",
    "slave of":         "#7F8C8D",
    "hired":            "#F39C12",
    "usurped":          "#C0392B",
    "plotted against":  "#C0392B",
    "debated with":     "#E67E22",
    "rebuked by":       "#E67E22",
    "fought":           "#E67E22",
    "besieged":         "#C0392B",
    "conquered":        "#C0392B",
    "exiled":           "#C0392B",
    "threw in furnace": "#C0392B",
    "deceived":         "#C0392B",
    "decreed return":   "#27AE60",
    "prophesied kingship": "#27AE60",
    "prophesied against": "#E67E22",
    "called in reign of": "#95A5A6",
    "carried cross for": "#AF7AC5",
    "released instead of": "#7F8C8D",
    "buried":           "#AF7AC5",
    "helped bury":      "#AF7AC5",
    "accused of using": "#C0392B",
    "healed daughter":  "#8E44AD",
    "replaced":         "#3498DB",
    "appealed for":     "#3498DB",
    "warned by":        "#E67E22",
    "fellow deacon":    "#3498DB",
    "answered by":      "#95A5A6",
    "overthrown by":    "#C0392B",
    "outwitted":        "#E67E22",
    "cursed":           "#C0392B",
    "protected":        "#27AE60",
    "vindicated":       "#27AE60",
    "assaulted":        "#C0392B",
    "mistress of":      "#E74C3C",
    "allied with":      "#3498DB",
    "falsely accused":  "#C0392B",
}

# Node colours by group
GROUP_COLOURS = {
    "patriarch":  "#2E86C1",
    "matriarch":  "#AF7AC5",
    "king":       "#F4D03F",
    "queen":      "#E74C3C",
    "prophet":    "#27AE60",
    "judge":      "#E67E22",
    "apostle":    "#3498DB",
    "evangelist": "#1ABC9C",
    "leader":     "#D35400",
    "priest":     "#8E44AD",
    "warrior":    "#E59866",
    "angel":      "#F7DC6F",
    "demon":      "#641E16",
    "other":      "#95A5A6",
}
